### ISSUE TITLE
FEAT: create the landing page to be shown after login

### ISSUE THREAD

**Issue by Markkos89** [zenbitETH/Croissant#3]
After the login with wallet flow, shown below

![image](https://github.com/zenbitETH/Croissant/assets/2791028/7dd22a1e-5fae-4b07-81c1-00c98204983c)

create the LandingPage with the following specifications,
this is the first page the logged users will see after successfull login

![image](https://github.com/zenbitETH/Croissant/assets/2791028/f917b54c-7f6d-467a-9beb-41481f9752fd)

Here the two blocks painted fucsia and green are representing:

- tabs for user role users
- tabs for admin role users

we also have to consider:

- common tabs for both roles
- common action buttons for both roles
- common setting/config for both roles

- the tabs are going to be conditionally render by the user role of the logged user

**Comment by HabacucMX** [comment]
Home can be the common tab for both roles, displaying basic data about the schema like # of attestations or the latest attestations made.

Also, admins can be attested even when they are admins. Then, the user tabs should be active for admins.

Not the same with the admin tabs that should be only accessible to admins
